default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASS"] %>
development:
  <<: *default
  database: cloudkh_development
test:
  <<: *default
  database: cloudkh_test
production:
  <<: *default
  database: cloudkh_production
  username: root
  password: 12240451
