timeout: 10800
retries: 5
users:
  per_page: 25.0
videos:
  status:
    done: 0
    progress: 1
    ban: 2
  mime_types:
    mp4: 0
    avi: 1
    mkv: 2
  per_page: 25.0
conditions:
  false: "false"
  true: "true"
paypal:
  payment_plan: "Basic"
  statuses:
    completed: "Completed"
    failed: "Failed"
    pending: "Pending"
drives:
  access_token: "access_token"
  user_id: "default"
  credentials:
    format: ".credentials"
    path: "lib/google_drive/"
  file: "0B8qFJJCJxA49UnlYR3JJQU9HcGs"
  timeout: 3300
  scopes:
    full: ['https://www.googleapis.com/auth/plus.me', 'https://www.googleapis.com/auth/userinfo.profile', 'https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/calendar', 'https://mail.google.com/', 'openid', 'email', 'profile']
    read_only: "https://www.googleapis.com/auth/drive.readonly"
  client_secret_paths:
    full: "lib/google_drive/client_secret.json"
    read_only: "lib/google_drive/client_secret_read.json"
  oob_uri: "http://dev.cloudkh.com/oauth2callback"
  application_name: "CloudKH"
  yamls:
    full: "cloudkh_full.yaml"
    read_only: "cloudkh_read.yaml"
